# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alan Lee
email: chenyalee1209@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a engineer in Taiwan.
  I'm also a Android developer freelancer.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alandrea1209.github.io/"

# Social
githubUsername: Alandrea1209
twitterUsername:
dribbbleUsername:
codepenUsername:
linkedinUsername: alanlee1209
# Build settings
markdown: kramdown


#theme: green # green, blue, orange, purple, grey
fixedNav: 'false' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages, _plugins]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
